export enum IconType {
	roundPlus = 'round_plus',
	roundMinus = 'round_minus',
	cross = 'cross',
	plus = 'plus',
	fill = 'fill',
	vertical = 'vertical',
	horizontal = 'horizontal',
	pin = 'pin',
	pencil = 'pencil',
	back = 'back',
	google = 'google',
	dots = 'dots',
	person = 'person',
	basket = 'basket',
	search = 'search',
}
