name: Drizzle Migrations

on:
    push:
        branches:
            - master
            - dev
        paths:
            - 'drizzle/**'
            - 'server/db/schema.ts'
            - 'scripts/migrate.ts'

jobs:
    migrate:
        name: Run DB migrations
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Setup Node.js
              uses: actions/setup-node@v5
              with:
                  node-version: 24
                  cache: npm

            - name: Install dependencies
              run: npm ci

            - name: Run migrations
              env:
                  NUXT_DATABASE_URL: ${{ secrets.NUXT_DATABASE_URL }}
              run: npm run db:migrate:prod
